# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de2fa1b39d41eb0051c02d27ad877bd6977b9d0e52636981fdc2ca586961d487665fff6a27bcd29a8c94fbe200ee34edb6ad3b2b206fcf82a00b8f9ade1f2d21
  dragonfly_dos_protection: efe219648781beea716b55423d2916b39275225b1b95741d0577737ea47e4960

test:
  secret_key_base: f4ecd741b2a554958c929a12fa3fc2635f8d65d6db6d5e3db4f46bbd3dd692161a7d3482a10fe148cfbe331e2118fb973cdad28991e3650cda31d1a813b45303

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  dragonfly_dos_protection:     <%= ENV["DRAGONFLY_DOS_PROTECTION"] %>
  dragonfly_bucket:             <%= ENV["DRAGONFLY_BUCKET"] %>
  dragonfly_access_key_id:      <%= ENV["DRAGONFLY_ACCESS_KEY_ID"] %>
  dragonfly_secret_access_key:  <%= ENV["DRAGONFLY_SECRET_ACCESS_KEY"] %>
